name: ds_common
description: Common library for sect.dev (https://sect.dev/)
version: 0.1.0
repository: https://github.com/al-tush/ds_common

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fimber: ^0.6.6
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.2.0
  shared_preferences: ^2.0.17
  userx_flutter: ^1.0.17
  appmetrica_plugin: ^1.0.1
  decimal: ^2.3.0
  package_info_plus: ^3.1.2
  firebase_remote_config: ^3.0.0
  firebase_analytics: ^10.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  tuple: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: pro.altush.ds_common
        pluginClass: DsCommonPlugin
      ios:
        pluginClass: DsCommonPlugin
