name: ds_common
description: Common library SectDev of Flutter projects (https://sect.dev/) - wraps Yandex Metrica, Firebase Crashlytics, RemoteConfig, Fimber, etc.
version: 0.1.11
repository: https://github.com/al-tush/ds_common

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fimber: ^0.7.0
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.2.0
  shared_preferences: ^2.0.17
  userx_flutter: ^1.1.0
  appmetrica_plugin: ^1.3.0
  decimal: ^2.3.0
  package_info_plus: ^4.0.2
  firebase_remote_config: ^4.0.0
  firebase_analytics: ^10.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  tuple: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: pro.altush.ds_common
        pluginClass: DsCommonPlugin
      ios:
        pluginClass: DsCommonPlugin
